// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Targv20Shop.Data;

namespace Targv20Shop.Data.Migrations
{
    [DbContext(typeof(Targv20ShopDbContext))]
    [Migration("20211115103444_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("CarVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Targv20Shop.Core.Domain.Car", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ModelName")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Year")
                    .HasColumnType("int");

                b.Property<string>("Engine")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Fuel")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Mileage")
                    .HasColumnType("int");

                b.Property<string>("Drive")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Transmission")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Color")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("VIN")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("ModifiedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Car");
            });
#pragma warning restore 612, 618
        }
    }
}